"""added applicant.py

Revision ID: 37f4cc821a07
Revises: d420f89b18b6
Create Date: 2026-07-26 01:28:50.452909

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f4cc821a07'
down_revision = 'd420f89b18b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

