"""added applicant.py

Revision ID: 37f4cc821a07
Revises: d420f89b18b6
Create Date: 2026-07-26 01:28:50.452909

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import TSTZRANGE
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '37f4cc821a07'
down_revision = 'd420f89b18b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'applicants',
        sa.Column(
            'id',
            postgresql.UUID(as_uuid=True),
            server_default=text("gen_random_uuid()"),
            nullable=False
        ),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("roles_of_interest", sa.ARRAY(sa.String(length=255)), nullable=True),
        sa.Column("first_committee", sa.String(length=255), nullable=True),
        sa.Column("second_committee", sa.String(length=255), nullable=True),
        sa.Column("third_committee", sa.String(length=255), nullable=True),
        sa.Column(
            "applicant_status",
            sa.Enum(
                "APPLIED",
                "INTERVIEW_TIMES_SENT",
                "INTERVIEW_TIMES_CONFIRMED",
                "INTERVIEW_CONFIRMED",
                "INTERVIEW_CONCLUDED",
                "INTERVIEW_RESCHEDULED",
                "ACCEPTED",
                "REJECTED",
                "OFFERED",
                "CONFIRMED",
                "WITHDRAWN",
                name="applicant_status_enum",
                native_enum=True
            ),
            nullable=False
        ),
        sa.Column("availability", sa.ARRAY(TSTZRANGE())),
        sa.PrimaryKeyConstraint("id")
    )

    op.create_index(op.f("ix_applicants_id"), "applicants", ["id"], unique=False)
    op.create_index(op.f("ix_applicants_email"), "applicants", ["email"], unique=True)


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_applicants_email"), table_name="applicants")
    op.drop_index(op.f("ix_applicants_id"), table_name="applicants")
    op.drop_table("applicants")
    op.execute("DROP TYPE IF EXISTS applicant_status_enum")

    # ### end Alembic commands ###

