"""create interview table

Revision ID: 3fc38ecd1085
Revises: cc5fbd660f2f
Create Date: 2026-07-26 19:09:16.430842

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = '3fc38ecd1085'
down_revision = 'cc5fbd660f2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('sec_member_id1', sa.UUID(), nullable=True),
    sa.Column('sec_member_id2', sa.UUID(), nullable=True),
    sa.Column('isConfirmed1', sa.Boolean(), nullable=True),
    sa.Column('isConfirmed2', sa.Boolean(), nullable=True),
    sa.Column('interviewDateTime', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sec_member_id1'], ['sec_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sec_member_id2'], ['sec_members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('applicant_id')
    )
    op.alter_column('applicants', 'first_committee',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('applicants', 'second_committee',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('applicants', 'third_committee',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('applicants', 'applicant_status',
               existing_type=ENUM('APPLIED', 'INTERVIEW_TIMES_SENT', 'INTERVIEW_TIMES_CONFIRMED', 'INTERVIEW_CONFIRMED', 'INTERVIEW_CONCLUDED', 'INTERVIEW_RESCHEDULED', 'ACCEPTED', 'REJECTED', 'OFFERED', 'CONFIRMED', 'WITHDRAWN', name='applicant_status_enum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applicants', 'applicant_status',
               existing_type=ENUM('APPLIED', 'INTERVIEW_TIMES_SENT', 'INTERVIEW_TIMES_CONFIRMED', 'INTERVIEW_CONFIRMED', 'INTERVIEW_CONCLUDED', 'INTERVIEW_RESCHEDULED', 'ACCEPTED', 'REJECTED', 'OFFERED', 'CONFIRMED', 'WITHDRAWN', name='applicant_status_enum'),
               nullable=False)
    op.alter_column('applicants', 'third_committee',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('applicants', 'second_committee',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('applicants', 'first_committee',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_table('interviews')
    # ### end Alembic commands ###

