"""added_images

Revision ID: 7e88398aa726
Revises: f55c0d42bec0
Create Date: 2026-03-23 22:40:08.100126

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e88398aa726'
down_revision = 'f55c0d42bec0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('committees', sa.Column('image_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('committees', 'image_url')
    # ### end Alembic commands ###

