"""sec member edits

Revision ID: 7f9b9c128399
Revises: d420f89b18b6
Create Date: 2026-07-20 19:39:12.111016

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7f9b9c128399"
down_revision = "d420f89b18b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sec_members",
        sa.Column(
            "interview_slots", sa.ARRAY(sa.DateTime(timezone=True)), nullable=True
        ),
    )
    op.add_column(
        "sec_members", sa.Column("interviewees", sa.ARRAY(sa.UUID()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sec_members", "interviewees")
    op.drop_column("sec_members", "interview_slots")
    # ### end Alembic commands ###
