"""describe change

Revision ID: 89cb89cf25b7
Revises: 0001_create_committees
Create Date: 2026-03-22 22:28:42.995707

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '89cb89cf25b7'
down_revision = '0001_create_committees'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_type WHERE typname = 'delegate_experience_enum'
            ) THEN
                CREATE TYPE delegate_experience_enum AS ENUM (
                    'Beginner', 'Intermediate', 'Expertise'
                );
            END IF;
        END $$;
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_type WHERE typname = 'delegate_status_enum'
            ) THEN
                CREATE TYPE delegate_status_enum AS ENUM (
                    'Awaiting Assignment', 'Assigned', 'Confirmed'
                );
            END IF;
        END $$;
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_type WHERE typname = 'event_type_enum'
            ) THEN
                CREATE TYPE event_type_enum AS ENUM ('Assignment', 'Email');
            END IF;
        END $$;
        """
    )

    op.add_column(
        'committees',
        sa.Column(
            'id_new',
            postgresql.UUID(as_uuid=True),
            nullable=False,
            server_default=sa.text('gen_random_uuid()'),
        ),
    )
    op.execute('UPDATE committees SET id_new = gen_random_uuid()')
    op.drop_index(op.f('ix_committees_id'), table_name='committees')
    op.drop_constraint('committees_pkey', 'committees', type_='primary')
    op.drop_column('committees', 'id')
    op.alter_column('committees', 'id_new', new_column_name='id')
    op.create_primary_key('committees_pkey', 'committees', ['id'])
    op.create_index(op.f('ix_committees_id'), 'committees', ['id'], unique=False)

    op.create_table('delegations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('faculty_advisor_first_name', sa.String(length=255), nullable=True),
    sa.Column('faculty_advisor_last_name', sa.String(length=255), nullable=True),
    sa.Column('faculty_advisor_email', sa.String(length=255), nullable=True),
    sa.Column('head_delegate_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delegations_id'), 'delegations', ['id'], unique=False)
    op.create_index(op.f('ix_delegations_name'), 'delegations', ['name'], unique=True)
    op.create_table('email_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject_template', sa.String(length=255), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('placeholders', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
    op.create_index(op.f('ix_email_templates_name'), 'email_templates', ['name'], unique=True)
    op.create_table('sec_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('last_logged_in', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sec_members_email'), 'sec_members', ['email'], unique=True)
    op.create_index(op.f('ix_sec_members_id'), 'sec_members', ['id'], unique=False)
    op.create_table('delegates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column(
        'delegate_experience',
        postgresql.ENUM(
            'Beginner',
            'Intermediate',
            'Expertise',
            name='delegate_experience_enum',
            create_type=False,
        ),
        nullable=False,
    ),
    sa.Column('first_committee', sa.String(length=255), nullable=True),
    sa.Column('second_committee', sa.String(length=255), nullable=True),
    sa.Column('third_committee', sa.String(length=255), nullable=True),
    sa.Column('date_applied', sa.DateTime(timezone=True), nullable=True),
    sa.Column(
        'delegate_status',
        postgresql.ENUM(
            'Awaiting Assignment',
            'Assigned',
            'Confirmed',
            name='delegate_status_enum',
            create_type=False,
        ),
        nullable=False,
    ),
    sa.Column('delegation_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['delegation_id'], ['delegations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delegates_email'), 'delegates', ['email'], unique=True)
    op.create_index(op.f('ix_delegates_id'), 'delegates', ['id'], unique=False)
    op.create_table('event_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sec_member_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column(
        'event_type',
        postgresql.ENUM(
            'Assignment',
            'Email',
            name='event_type_enum',
            create_type=False,
        ),
        nullable=False,
    ),
    sa.Column('target_type', sa.String(length=255), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sec_member_id'], ['sec_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_id'), 'event_logs', ['id'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('committee_id', sa.UUID(), nullable=False),
    sa.Column('delegate_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.ForeignKeyConstraint(['delegate_id'], ['delegates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delegate_id')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.add_column('committees', sa.Column('small_description', sa.String(length=512), nullable=True))
    op.add_column('committees', sa.Column('large_description', sa.Text(), nullable=True))
    op.add_column('committees', sa.Column('director_name', sa.String(length=255), nullable=True))
    op.add_column('committees', sa.Column('chair_name', sa.String(length=255), nullable=True))
    op.add_column('committees', sa.Column('crisis_analysts', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('committees', sa.Column('max_delegates', sa.Integer(), nullable=True))
    op.add_column('committees', sa.Column('background_guide_link', sa.String(length=1024), nullable=True))
    op.add_column('committees', sa.Column('mechanics_guide_link', sa.String(length=1024), nullable=True))
    op.add_column('committees', sa.Column('character_guide_link', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('committees', 'character_guide_link')
    op.drop_column('committees', 'mechanics_guide_link')
    op.drop_column('committees', 'background_guide_link')
    op.drop_column('committees', 'max_delegates')
    op.drop_column('committees', 'crisis_analysts')
    op.drop_column('committees', 'chair_name')
    op.drop_column('committees', 'director_name')
    op.drop_column('committees', 'large_description')
    op.drop_column('committees', 'small_description')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_event_logs_id'), table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index(op.f('ix_delegates_id'), table_name='delegates')
    op.drop_index(op.f('ix_delegates_email'), table_name='delegates')
    op.drop_table('delegates')
    op.drop_index(op.f('ix_sec_members_id'), table_name='sec_members')
    op.drop_index(op.f('ix_sec_members_email'), table_name='sec_members')
    op.drop_table('sec_members')
    op.drop_index(op.f('ix_email_templates_name'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_id'), table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_index(op.f('ix_delegations_name'), table_name='delegations')
    op.drop_index(op.f('ix_delegations_id'), table_name='delegations')
    op.drop_table('delegations')

    op.drop_index(op.f('ix_committees_id'), table_name='committees')
    op.drop_constraint('committees_pkey', 'committees', type_='primary')
    op.add_column('committees', sa.Column('id_old', sa.Integer(), nullable=False))
    op.execute('UPDATE committees SET id_old = nextval(''committees_id_seq'')')
    op.drop_column('committees', 'id')
    op.alter_column('committees', 'id_old', new_column_name='id')
    op.create_primary_key('committees_pkey', 'committees', ['id'])
    op.create_index(op.f('ix_committees_id'), 'committees', ['id'], unique=False)

    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_type WHERE typname = 'event_type_enum'
            ) THEN
                DROP TYPE event_type_enum;
            END IF;
        END $$;
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_type WHERE typname = 'delegate_status_enum'
            ) THEN
                DROP TYPE delegate_status_enum;
            END IF;
        END $$;
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_type WHERE typname = 'delegate_experience_enum'
            ) THEN
                DROP TYPE delegate_experience_enum;
            END IF;
        END $$;
        """
    )
    # ### end Alembic commands ###

