"""foreign-key-cascade

Revision ID: 8f6a0ef36163
Revises: b4c8992f9eca
Create Date: 2026-07-17 18:58:05.678698

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6a0ef36163'
down_revision = 'b4c8992f9eca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('characters_committee_id_fkey', 'characters', type_='foreignkey')
    op.drop_constraint('characters_delegate_id_fkey', 'characters', type_='foreignkey')
    op.create_foreign_key(None, 'characters', 'committees', ['committee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'characters', 'delegates', ['delegate_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('delegates_delegation_id_fkey', 'delegates', type_='foreignkey')
    op.create_foreign_key(None, 'delegates', 'delegations', ['delegation_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('event_logs_sec_member_id_fkey', 'event_logs', type_='foreignkey')
    op.create_foreign_key(None, 'event_logs', 'sec_members', ['sec_member_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_logs', type_='foreignkey')
    op.create_foreign_key('event_logs_sec_member_id_fkey', 'event_logs', 'sec_members', ['sec_member_id'], ['id'])
    op.drop_constraint(None, 'delegates', type_='foreignkey')
    op.create_foreign_key('delegates_delegation_id_fkey', 'delegates', 'delegations', ['delegation_id'], ['id'])
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.create_foreign_key('characters_delegate_id_fkey', 'characters', 'delegates', ['delegate_id'], ['id'])
    op.create_foreign_key('characters_committee_id_fkey', 'characters', 'committees', ['committee_id'], ['id'])
    # ### end Alembic commands ###

