"""add sec availability

Revision ID: a02681a0a01f
Revises: 7f9b9c128399
Create Date: 2026-07-25 02:59:42.621649

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a02681a0a01f'
down_revision = '7f9b9c128399'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sec_members', sa.Column('availability', sa.ARRAY(sa.DateTime(timezone=True), dimensions=2), nullable=True))
    op.drop_column('sec_members', 'interviewees')
    op.drop_column('sec_members', 'interview_slots')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sec_members', sa.Column('interview_slots', sa.ARRAY(sa.TIMESTAMP(timezone=True)), autoincrement=False, nullable=True))
    op.add_column('sec_members', sa.Column('interviewees', sa.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.drop_column('sec_members', 'availability')
    # ### end Alembic commands ###

