"""add_confirms_payment_to_email_templates

Revision ID: c68434c91f34
Revises: a4e6c8d0f2b1
Create Date: 2026-07-18 17:38:13.115448

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c68434c91f34"
down_revision = "a4e6c8d0f2b1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_templates",
        sa.Column(
            "confirms_payment",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("email_templates", "confirms_payment")
    # ### end Alembic commands ###
