"""initial_squash

Revision ID: f55c0d42bec0
Revises:
Create Date: 2026-03-23 22:26:22.348645

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = "f55c0d42bec0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.create_table(
        "committees",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("small_description", sa.String(length=512), nullable=False),
        sa.Column("large_description", sa.Text(), nullable=False),
        sa.Column("director_name", sa.String(length=255), nullable=False),
        sa.Column("chair_name", sa.String(length=255), nullable=True),
        sa.Column(
            "crisis_analysts", postgresql.ARRAY(sa.String(length=255)), nullable=True
        ),
        sa.Column("max_delegates", sa.Integer(), nullable=True),
        sa.Column("background_guide_link", sa.String(length=1024), nullable=True),
        sa.Column("mechanics_guide_link", sa.String(length=1024), nullable=True),
        sa.Column("character_guide_link", sa.String(length=1024), nullable=True),
        sa.Column("image_url", sa.String(length=1024), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_committees_id"), "committees", ["id"], unique=False)
    op.create_index(op.f("ix_committees_name"), "committees", ["name"], unique=True)

    op.create_table(
        "delegations",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("faculty_advisor_first_name", sa.String(length=255), nullable=False),
        sa.Column("faculty_advisor_last_name", sa.String(length=255), nullable=False),
        sa.Column("faculty_advisor_email", sa.String(length=255), nullable=False),
        sa.Column("head_delegate_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_delegations_id"), "delegations", ["id"], unique=False)
    op.create_index(op.f("ix_delegations_name"), "delegations", ["name"], unique=True)

    op.create_table(
        "sec_members",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=255), nullable=False),
        sa.Column("last_logged_in", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sec_members_id"), "sec_members", ["id"], unique=False)
    op.create_index(op.f("ix_sec_members_email"), "sec_members", ["email"], unique=True)

    op.create_table(
        "delegates",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("preferred_name", sa.String(length=255), nullable=True),
        sa.Column("grade", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "delegate_experience",
            sa.Enum(
                "BEGINNER",
                "INTERMEDIATE",
                "EXPERTISE",
                name="delegate_experience_enum",
                native_enum=True,
            ),
            nullable=False,
        ),
        sa.Column("first_committee", sa.String(length=255), nullable=False),
        sa.Column("second_committee", sa.String(length=255), nullable=False),
        sa.Column("third_committee", sa.String(length=255), nullable=False),
        sa.Column("date_applied", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "delegate_status",
            sa.Enum(
                "AWAITING_ASSIGNMENT",
                "ASSIGNED",
                "CONFIRMED",
                name="delegate_status_enum",
                native_enum=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "delegation_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("delegations.id"),
            nullable=True,
        ),
        sa.Column("code_of_conduct_url", sa.String(length=1024), nullable=True),
        sa.Column("payment_policy_ack", sa.Boolean(), nullable=True),
        sa.Column("cancellation_policy_ack", sa.Boolean(), nullable=True),
        sa.Column("heard_about", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_delegates_id"), "delegates", ["id"], unique=False)
    op.create_index(op.f("ix_delegates_email"), "delegates", ["email"], unique=True)

    op.create_table(
        "event_logs",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "sec_member_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("sec_members.id"),
            nullable=True,
        ),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=text("now()"),
            nullable=False,
        ),
        sa.Column(
            "event_type",
            sa.Enum(
                "ASSIGNMENT",
                "EMAIL",
                "COMMITTEE_UPDATE",
                name="event_type_enum",
                native_enum=True,
            ),
            nullable=False,
        ),
        sa.Column("target_type", sa.String(length=255), nullable=True),
        sa.Column("target_id", sa.String(length=255), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_logs_id"), "event_logs", ["id"], unique=False)

    op.create_table(
        "email_templates",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("subject_template", sa.String(length=255), nullable=False),
        sa.Column("body_template", sa.Text(), nullable=False),
        sa.Column(
            "placeholders", postgresql.ARRAY(sa.String(length=255)), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_templates_id"), "email_templates", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_email_templates_name"), "email_templates", ["name"], unique=True
    )

    op.create_table(
        "characters",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "committee_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("committees.id"),
            nullable=False,
        ),
        sa.Column(
            "delegate_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("delegates.id"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("delegate_id"),
    )
    op.create_index(op.f("ix_characters_id"), "characters", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_characters_id"), table_name="characters")
    op.drop_table("characters")
    op.drop_index(op.f("ix_email_templates_name"), table_name="email_templates")
    op.drop_index(op.f("ix_email_templates_id"), table_name="email_templates")
    op.drop_table("email_templates")
    op.drop_index(op.f("ix_event_logs_id"), table_name="event_logs")
    op.drop_table("event_logs")
    op.drop_index(op.f("ix_delegates_email"), table_name="delegates")
    op.drop_index(op.f("ix_delegates_id"), table_name="delegates")
    op.drop_table("delegates")
    op.drop_index(op.f("ix_sec_members_email"), table_name="sec_members")
    op.drop_index(op.f("ix_sec_members_id"), table_name="sec_members")
    op.drop_table("sec_members")
    op.drop_index(op.f("ix_delegations_name"), table_name="delegations")
    op.drop_index(op.f("ix_delegations_id"), table_name="delegations")
    op.drop_table("delegations")
    op.drop_index(op.f("ix_committees_name"), table_name="committees")
    op.drop_index(op.f("ix_committees_id"), table_name="committees")
    op.drop_table("committees")
    op.execute("DROP TYPE IF EXISTS event_type_enum")
    op.execute("DROP TYPE IF EXISTS delegate_status_enum")
    op.execute("DROP TYPE IF EXISTS delegate_experience_enum")
    # ### end Alembic commands ###
